In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
def get_spam_number(x):
  if x=='spam':
    return 1
  return 0

In [6]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [9]:
X_train.shape

(4457,)

In [10]:
X_test.shape

(1115,)

In [11]:
type(X_train)

pandas.core.series.Series

In [12]:
X_train[:4]

5186                          I uploaded mine to Facebook
3221    Its like that hotel dusk game i think. You sol...
4216                           No dear i was sleeping :-P
2223    Great. I was getting worried about you. Just k...
Name: Message, dtype: object

In [13]:
type(y_train.values)

numpy.ndarray

In [14]:
y_train[:4]

5186    0
3221    0
4216    0
2223    0
Name: spam, dtype: int64

In [15]:
X_train.values

array(['I uploaded mine to Facebook',
       'Its like that hotel dusk game i think. You solve puzzles in a area thing',
       'No dear i was sleeping :-P', ...,
       'Some are lasting as much as 2 hours. You might get lucky.',
       "Yupz... I've oredi booked slots 4 my weekends liao...",
       "Sorry, I'll call later"], dtype=object)

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7736 sparse matrix of type '<class 'numpy.int64'>'
	with 59446 stored elements in Compressed Sparse Row format>

In [17]:
#X_train_cv.toarray()
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [18]:
X_train_cv.shape

(4457, 7736)

In [19]:
v.get_feature_names_out()[1000:1050]

array(['animation', 'anjola', 'anna', 'annie', 'anniversary',
       'annoncement', 'announcement', 'annoyin', 'annoying', 'anonymous',
       'anot', 'another', 'ans', 'ansr', 'answer', 'answered', 'answerin',
       'answering', 'answers', 'answr', 'antelope', 'antha', 'anthony',
       'anti', 'antibiotic', 'any', 'anybody', 'anyhow', 'anymore',
       'anyone', 'anyones', 'anythiing', 'anything', 'anythingtomorrow',
       'anytime', 'anyway', 'anyways', 'anywhere', 'aom', 'apart',
       'apartment', 'apes', 'apeshit', 'aphex', 'apo', 'apologetic',
       'apologise', 'apologize', 'apology', 'app'], dtype=object)

In [26]:
#v.get_feature_names_out().shape
v.get_feature_names_out()[3541]

'houseful'

In [22]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [23]:
v.vocabulary_

{'uploaded': 7198,
 'mine': 4507,
 'to': 6934,
 'facebook': 2762,
 'its': 3791,
 'like': 4140,
 'that': 6810,
 'hotel': 3533,
 'dusk': 2509,
 'game': 3087,
 'think': 6843,
 'you': 7699,
 'solve': 6297,
 'puzzles': 5529,
 'in': 3668,
 'area': 1082,
 'thing': 6841,
 'no': 4813,
 'dear': 2209,
 'was': 7394,
 'sleeping': 6222,
 'great': 3256,
 'getting': 3147,
 'worried': 7595,
 'about': 780,
 'just': 3899,
 'know': 3988,
 'wonderful': 7576,
 'and': 993,
 'caring': 1693,
 'person': 5180,
 'will': 7515,
 'have': 3379,
 'only': 4963,
 'the': 6814,
 'best': 1361,
 'life': 4129,
 'god': 3190,
 'love': 4248,
 'is': 3773,
 'yours': 7707,
 'called': 1643,
 'dad': 2160,
 'oredi': 5003,
 'am': 965,
 'marriage': 4384,
 'function': 3063,
 'collecting': 1914,
 'ur': 7204,
 'laptop': 4045,
 'then': 6824,
 'going': 3197,
 'configure': 1979,
 'da': 2157,
 'settings': 6046,
 'izzit': 3800,
 'yeah': 7673,
 'we': 7418,
 'do': 2390,
 'totes': 6998,
 'when': 7479,
 'wanna': 7378,
 'hows': 3549,
 'street': 652

In [27]:
X_train_cv[0]

<1x7736 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [36]:
X_train_np=X_train_cv.toarray()
#X_train_np[:4][0]
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [35]:
#np.where(X_train_np)
np.where(X_train_np[0]!=0)

(array([2762, 4507, 6934, 7198]),)

In [41]:
X_train[:4][5186]

'I uploaded mine to Facebook'

In [44]:
X_train_np[0][2762]

1

In [49]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [50]:
X_test_cv=v.transform(X_test)

In [52]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       973
           1       0.96      0.94      0.95       142

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [53]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count=v.transform(emails)
model.predict(emails_count)


array([0, 1])

In [54]:
from sklearn.pipeline import Pipeline

clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [55]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [56]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       973
           1       0.96      0.94      0.95       142

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

